# Generated by Django 4.2.6 on 2023-10-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField()),
                ("pos", models.CharField(max_length=100)),
                ("award", models.IntegerField()),
                ("content", models.CharField(max_length=10000)),
                ("skills", models.CharField(max_length=100)),
            ],
        ),
    ]
