# Generated by Django 4.2.6 on 2023-10-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wanted_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="pos",
            new_name="position",
        ),
        migrations.AlterField(
            model_name="item",
            name="company_id",
            field=models.IntegerField(editable=False),
        ),
    ]
