# Generated by Django 4.2.6 on 2023-10-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wanted_api", "0002_rename_pos_item_position_alter_item_company_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="position",
            new_name="job_position",
        ),
    ]
